// <auto-generated />
using System;
using Fitness_Tracker_API.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fitness_Tracker_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250514125207_Fixed_Food_Model")]
    partial class Fixed_Food_Model
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExcerciseTargetedMuscleGroup", b =>
                {
                    b.Property<int>("ExcercisesId")
                        .HasColumnType("int");

                    b.Property<int>("TargetedMuscleGroupsId")
                        .HasColumnType("int");

                    b.HasKey("ExcercisesId", "TargetedMuscleGroupsId");

                    b.HasIndex("TargetedMuscleGroupsId");

                    b.ToTable("ExcerciseTargetedMuscleGroup");
                });

            modelBuilder.Entity("Fitness_Tracker_API.DataLayer.Models.BodyMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("BicepsCm")
                        .HasColumnType("float");

                    b.Property<double?>("ChestCm")
                        .HasColumnType("float");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<double?>("HipsCm")
                        .HasColumnType("float");

                    b.Property<double?>("ThighsCm")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<double?>("WaistCm")
                        .HasColumnType("float");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BodyMeasurements");
                });

            modelBuilder.Entity("Fitness_Tracker_API.DataLayer.Models.ConsumedFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<int>("MealId")
                        .HasColumnType("int");

                    b.Property<byte>("ServingPortionInGrams")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("MealId");

                    b.ToTable("ConsumedFood");
                });

            modelBuilder.Entity("Fitness_Tracker_API.DataLayer.Models.DailyNutritionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DailyNutritionLogs");
                });

            modelBuilder.Entity("Fitness_Tracker_API.DataLayer.Models.Excercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfEquipment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfExcercise")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Excercises");
                });

            modelBuilder.Entity("Fitness_Tracker_API.DataLayer.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Calories")
                        .HasColumnType("real");

                    b.Property<float>("CarbsGrams")
                        .HasColumnType("real");

                    b.Property<float>("FatGrams")
                        .HasColumnType("real");

                    b.Property<float>("FiberGrams")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ProteinGrams")
                        .HasColumnType("real");

                    b.Property<int>("ServingInGrams")
                        .HasColumnType("int");

                    b.Property<float>("SugarGrams")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("Fitness_Tracker_API.DataLayer.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DailyNutritionLogId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("DailyNutritionLogId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("Fitness_Tracker_API.DataLayer.Models.TargetedMuscleGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TargetedMuscleGroups");
                });

            modelBuilder.Entity("Fitness_Tracker_API.DataLayer.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Fitness_Tracker_API.DataLayer.Models.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("Fitness_Tracker_API.DataLayer.Models.WorkoutExcercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExcerciseId")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExcerciseId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutExcercises");
                });

            modelBuilder.Entity("Fitness_Tracker_API.DataLayer.Models.WorkoutSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte?>("DurationInMinutes")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("IntensityOutOfTen")
                        .HasColumnType("tinyint");

                    b.Property<bool?>("IsWarmUpSet")
                        .HasColumnType("bit");

                    b.Property<byte?>("Reps")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("RepsInReserve")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("WeightInKg")
                        .HasColumnType("tinyint");

                    b.Property<int>("WorkoutExcerciseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutExcerciseId");

                    b.ToTable("WorkoutSets");
                });

            modelBuilder.Entity("ExcerciseTargetedMuscleGroup", b =>
                {
                    b.HasOne("Fitness_Tracker_API.DataLayer.Models.Excercise", null)
                        .WithMany()
                        .HasForeignKey("ExcercisesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fitness_Tracker_API.DataLayer.Models.TargetedMuscleGroup", null)
                        .WithMany()
                        .HasForeignKey("TargetedMuscleGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fitness_Tracker_API.DataLayer.Models.BodyMeasurement", b =>
                {
                    b.HasOne("Fitness_Tracker_API.DataLayer.Models.User", "User")
                        .WithMany("BodyMeasurements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fitness_Tracker_API.DataLayer.Models.ConsumedFood", b =>
                {
                    b.HasOne("Fitness_Tracker_API.DataLayer.Models.Food", "Food")
                        .WithMany("ConsumedFood")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fitness_Tracker_API.DataLayer.Models.Meal", "Meal")
                        .WithMany("ConsumedFood")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("Fitness_Tracker_API.DataLayer.Models.DailyNutritionLog", b =>
                {
                    b.HasOne("Fitness_Tracker_API.DataLayer.Models.User", "User")
                        .WithMany("DailyNutritionLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fitness_Tracker_API.DataLayer.Models.Meal", b =>
                {
                    b.HasOne("Fitness_Tracker_API.DataLayer.Models.DailyNutritionLog", "DailyNutritionLog")
                        .WithMany("Meals")
                        .HasForeignKey("DailyNutritionLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyNutritionLog");
                });

            modelBuilder.Entity("Fitness_Tracker_API.DataLayer.Models.Workout", b =>
                {
                    b.HasOne("Fitness_Tracker_API.DataLayer.Models.User", "User")
                        .WithMany("Workouts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fitness_Tracker_API.DataLayer.Models.WorkoutExcercise", b =>
                {
                    b.HasOne("Fitness_Tracker_API.DataLayer.Models.Excercise", "Excercise")
                        .WithMany("WorkoutExcercises")
                        .HasForeignKey("ExcerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fitness_Tracker_API.DataLayer.Models.Workout", "Workout")
                        .WithMany("WorkoutExcercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Excercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("Fitness_Tracker_API.DataLayer.Models.WorkoutSet", b =>
                {
                    b.HasOne("Fitness_Tracker_API.DataLayer.Models.WorkoutExcercise", "WorkoutExcercise")
                        .WithMany("WorkoutSets")
                        .HasForeignKey("WorkoutExcerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutExcercise");
                });

            modelBuilder.Entity("Fitness_Tracker_API.DataLayer.Models.DailyNutritionLog", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("Fitness_Tracker_API.DataLayer.Models.Excercise", b =>
                {
                    b.Navigation("WorkoutExcercises");
                });

            modelBuilder.Entity("Fitness_Tracker_API.DataLayer.Models.Food", b =>
                {
                    b.Navigation("ConsumedFood");
                });

            modelBuilder.Entity("Fitness_Tracker_API.DataLayer.Models.Meal", b =>
                {
                    b.Navigation("ConsumedFood");
                });

            modelBuilder.Entity("Fitness_Tracker_API.DataLayer.Models.User", b =>
                {
                    b.Navigation("BodyMeasurements");

                    b.Navigation("DailyNutritionLogs");

                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("Fitness_Tracker_API.DataLayer.Models.Workout", b =>
                {
                    b.Navigation("WorkoutExcercises");
                });

            modelBuilder.Entity("Fitness_Tracker_API.DataLayer.Models.WorkoutExcercise", b =>
                {
                    b.Navigation("WorkoutSets");
                });
#pragma warning restore 612, 618
        }
    }
}
